const list = [
  {
    id: 'vbyr3r2x76803',
    title: 'Новый день — новые возможности',
    text: 'Каждое утро — шанс начать заново. Не упускайте его!',
    date: '2025-11-10T08:15:00Z',
    author: 'Motivation Daily',
    nickname: 'motivation_daily',
    image: 'https://example.com/images/sunrise.jpg',
    thumbnail: 'sunrise.jpg',
    ups: 6,
    lang: 'ru',
  },
  {
    id: 'yvn18s6x76803',
    title: 'Технологии будущего уже здесь',
    text: 'Искусственный интеллект меняет мир быстрее, чем мы думаем. Готовы ли вы?',
    date: '2025-11-10T09:30:00Z',
    author: 'Tech Insider',
    nickname: 'tech_insider',
    image: 'https://example.com/images/ai_future.jpg',
    thumbnail: 'ai_future.jpg',
    ups: 2,
    lang: 'ru',
  },
  {
    id: 'kgc69pux76803',
    title: 'Цитата дня',
    text: '«Не ждите идеального момента. Начните сейчас.» — Марк Мэнсон',
    date: '2025-11-10T10:00:00Z',
    author: 'Quote Master',
    nickname: 'quote_master',
    image: 'https://example.com/images/quote_bg.jpg',
    thumbnail: 'quote_bg.jpg',
    ups: 51,
    lang: 'ru',
  },
  {
    id: 'a2x3xctx76803',
    title: 'Совет для продуктивности',
    text: 'Работайте по 25 минут без отвлечений, затем отдыхайте 5. Метод Помидора работает!',
    date: '2025-11-10T11:20:00Z',
    author: 'Productivity Guru',
    nickname: 'productivity_guru',
    image: 'https://example.com/images/pomodoro.jpg',
    thumbnail: 'pomodoro.jpg',
    ups: 36,
    lang: 'ru',
  },
  {
    id: 'ny3yv9bx76803',
    title: 'Космос зовёт',
    text: 'NASA анонсировала новую миссию на Марс! Старт запланирован на 2028 год.',
    date: '2025-11-10T12:45:00Z',
    author: 'Space News',
    nickname: 'space_news',
    image: 'https://example.com/images/mars_mission.jpg',
    thumbnail: 'mars_mission.jpg',
    ups: 25,
    lang: 'ru',
  },
  {
    id: 'pdpoo5gx76803',
    title: 'Рецепт дня: Авокадо-тост',
    text: 'Просто, быстро и вкусно! Намажьте авокадо на тост, посыпьте чёрным перцем и сбрызните лимоном.',
    date: '2025-11-10T13:10:00Z',
    author: 'Easy Recipes',
    nickname: 'easy_recipes',
    image: 'https://example.com/images/avocado_toast.jpg',
    thumbnail: 'avocado_toast.jpg',
    ups: 15,
    lang: 'ru',
  },
  {
    id: '6jtzrfkx76803',
    title: 'Фото дня',
    text: 'Закат в горах — лучшее лекарство от стресса.',
    date: '2025-11-10T15:00:00Z',
    author: 'Nature Daily',
    nickname: 'nature_daily',
    image: 'https://example.com/images/sunset_mountains.jpg',
    thumbnail: 'sunset_mountains.jpg',
    ups: 21,
    lang: 'ru',
  },
  {
    id: 'feniy23x76803',
    title: 'Полезная привычка',
    text: 'Пишите 3 вещи, за которые вы благодарны, каждый вечер. Это работает!',
    date: '2025-11-10T16:30:00Z',
    author: 'Mindful Living',
    nickname: 'mindful_living',
    image: 'https://example.com/images/gratitude.jpg',
    thumbnail: 'gratitude.jpg',
    ups: 16,
    lang: 'ru',
  },
  {
    id: '9ddv607x76803',
    title: 'Кибербезопасность',
    text: 'Никогда не используйте один и тот же пароль для разных аккаунтов. Пора обновить свои привычки!',
    date: '2025-11-10T17:45:00Z',
    author: 'Cyber Safe',
    nickname: 'cyber_safe',
    image: 'https://example.com/images/password_security.jpg',
    thumbnail: 'password_security.jpg',
    ups: 15,
    lang: 'ru',
  },
  {
    id: 'vw8ekdxx76803',
    title: 'Музыкальная рекомендация',
    text: "Откройте для себя альбом 'Midnight Vibes' — идеальный саундтрек для тихого вечера.",
    date: '2025-11-10T19:00:00Z',
    author: 'Music Mood',
    nickname: 'music_mood',
    image: 'https://example.com/images/midnight_vibes.jpg',
    thumbnail: 'midnight_vibes.jpg',
    ups: 52,
    lang: 'ru',
  },
  {
    id: '7a2yep2x76803',
    title: 'Why learning a new language changed my brain',
    text: 'I started learning Spanish at 32, thinking it would be impossible. Two years later, I’m fluent enough to dream in it! But the real surprise wasn’t just communication — it was how my brain changed. I became better at multitasking, noticed improvements in memory, and even started thinking more creatively. Neuroscientists say bilingualism builds cognitive reserve, delaying dementia by years. The key? Consistency over intensity. I used apps for 15 minutes daily, watched telenovelas with subtitles, and chatted with native speakers online. No pressure, just curiosity. If you’re hesitating because you’re “too old” — stop. Your brain is plastic at any age. Language isn’t just words; it’s a window into another way of seeing the world. Try it. Even 10 minutes a day adds up to fluency faster than you think.',
    date: '2025-02-28T14:40:00Z',
    author: 'Emily Johnson',
    nickname: 'polyglot_em',
    image: 'https://example.com/images/spanish_books.jpg',
    thumbnail: 'spanish_books.jpg',
    ups: 45,
    lang: 'eng',
  },
  {
    id: 'r13qts4x76803',
    title: 'Как я прошёл путь от хаоса к порядку',
    text: 'В прошлом году моя жизнь была сплошным беспорядком: дедлайны горели, сон сбивался, а мысли путались. Я начал с малого — уборка стола каждое утро. Потом добавил планировщик задач и режим сна. Через три месяца заметил, что стал спокойнее, продуктивнее и даже начал читать книги. Главный секрет? Не пытайтесь изменить всё сразу. Выберите одну привычку и внедряйте её в течение 30 дней без перерыва. Не пропускайте ни дня — даже если делаете минимальный шаг. Со временем это вырастает в систему, которая поддерживает вас. Я не стал идеальным, но теперь у меня есть структура. А структура — это свобода от постоянного стресса. Если вы чувствуете, что тонете в рутине, начните с одного маленького правила. Оно станет якорем в бурю. Поверьте — это работает.',
    date: '2025-01-12T09:23:00Z',
    author: 'Михаил Минковский',
    nickname: 'ordered_mind',
    image: 'https://example.com/images/desk_organized.jpg',
    thumbnail: 'desk_organized.jpg',
    ups: 48,
    lang: 'ru',
  },
  {
    id: '314g37dx76803',
    title: 'Зачем я удалил все соцсети на месяц',
    text: 'Моя цель была простой — проверить, насколько я зависим от ленты. Первые три дня были мучительными: тревога, скука, желание “заглянуть на секунду”. Но к концу первой недели я начал замечать перемены. Я снова читал книги, гулял без телефона, разговаривал с друзьями лицом к лицу. Я стал замечать детали вокруг: как свет играет на листве, как звучит дождь. По возвращении я не стал восстанавливать всё — оставил только два аккаунта и отключил уведомления. Теперь я трачу в среднем 20 минут в день вместо трёх часов. Самое главное: я снова чувствую контроль над своим вниманием. А внимание — это самая ценная валюта в 21 веке. Если вы чувствуете, что теряете время, попробуйте хотя бы недельный перерыв. Вы удивитесь, сколько жизни происходит вне экрана.',
    date: '2025-04-05T11:15:00Z',
    author: 'Артём Семёнов',
    nickname: 'offline_art',
    image: 'https://example.com/images/phone_in_drawer.jpg',
    thumbnail: 'phone_in_drawer.jpg',
    ups: 41,
    lang: 'ru',
  },
  {
    id: 'hjezovzx76803',
    title: 'The quiet power of walking',
    text: 'In a world obsessed with optimization, walking is the most underrated productivity tool. No gear, no subscription, no learning curve. Just put on shoes and go. I walk 45 minutes every morning — no podcast, no music, just silence. It’s during these walks that my best ideas emerge. Studies show walking boosts creative thinking by up to 60%. It also lowers cortisol, improves posture, and gently resets your nervous system. You don’t need to hike mountains — a city park or quiet street works. The key is presence: feel your steps, notice your breath, observe without judging. Over time, walking becomes a moving meditation. Try it for a week. You might solve that problem that’s been stuck in your head for months — or simply remember what it feels like to be calm.',
    date: '2025-05-17T08:50:00Z',
    author: 'Daniel Reed',
    nickname: 'walk_thinker',
    image: 'https://example.com/images/morning_walk.jpg',
    thumbnail: 'morning_walk.jpg',
    ups: 38,
    lang: 'eng',
  },
  {
    id: 'xi6k0lcx76803',
    title: 'Как готовить быстро и вкусно без рецептов',
    text: 'Я перестал следовать рецептам и начал понимать кулинарию. Основа всего — баланс: кислое, солёное, сладкое, горькое, умами. Начните с обжарки лука и чеснока — это основа сотен блюд. Добавьте овощи, белок (тофу, яйцо, курица), зелень и специи. Соус? Смешайте лимонный сок, оливковое масло, горчицу и мёд. Готовьте на глаз — доверяйте вкусу. Со временем вы будете создавать блюда за 15 минут, не заглядывая в телефон. Главное — не бояться экспериментировать. Подгорело? Ничего страшного. Вкус не идеален? Завтра будет лучше. Кулинария — это не химия, это интуиция. А ещё — это любовь к себе. Потому что готовить для себя — значит заботиться о себе.',
    date: '2025-06-22T19:05:00Z',
    author: 'Софья Кузнецова',
    nickname: 'instinct_cook',
    image: 'https://example.com/images/home_cooking.jpg',
    thumbnail: 'home_cooking.jpg',
    ups: 33,
    lang: 'ru',
  },
  {
    id: 'f5960blx76803',
    title: 'Why I switched to paper notebooks',
    text: 'After years of digital notes, I went back to paper — and it transformed my thinking. On screens, I skim. On paper, I slow down. Writing by hand engages memory and creativity in ways typing never could. I use one notebook for ideas, one for daily reflections, and one for project planning. No distractions, no notifications, just ink and thought. Yes, it’s not searchable — but that’s the point. I remember more because I process more. And there’s something deeply satisfying about flipping through pages filled with your own journey. Try it for one week: write your to-do list, journal, or meeting notes by hand. You might rediscover the joy of thinking deeply in a shallow world.',
    date: '2025-07-14T10:30:00Z',
    author: 'James Carter',
    nickname: 'analog_james',
    image: 'https://example.com/images/paper_notebook.jpg',
    thumbnail: 'paper_notebook.jpg',
    ups: 29,
    lang: 'eng',
  },
  {
    id: 'usappcvx76803',
    title: 'Минимализм — это не про пустоту',
    text: 'Многие думают, что минимализм — это белые стены и одна чашка. Но на самом деле это про осознанность. Это про то, чтобы оставить только то, что действительно важно: вещи, отношения, привычки. Я избавился от 70% своих вещей и не пожалел. Но главная чистка произошла в голове — я перестал гнаться за “больше”. Теперь у меня меньше тревог, больше времени и ясности. Минимализм не требует жертв — он освобождает. Вы не обязаны жить в пустой комнате. Просто спрашивайте себя: “Это приносит мне пользу или радость?” Если нет — отпустите. Жизнь становится легче, когда вы перестаёте носить ненужный груз.',
    date: '2025-08-30T16:20:00Z',
    author: 'Екатерина Орлова',
    nickname: 'light_life_katya',
    image: 'https://example.com/images/minimal_room.jpg',
    thumbnail: 'minimal_room.jpg',
    ups: 24,
    lang: 'ru',
  },
  {
    id: '6yklkgxx76803',
    title: "The myth of 'natural talent'",
    text: 'People say, “You’re so talented!” when they see skill. But talent is mostly invisible practice. I spent 10,000 hours drawing before anyone noticed. What looks like genius is usually consistency, feedback, and the courage to make bad work first. Stop waiting to “feel ready.” Start before you’re good. Embrace the ugly phase — it’s necessary. Every expert was once a beginner who didn’t quit. Your only job is to show up regularly. Progress compounds silently. One day, someone will call you “talented” — and you’ll smile, knowing the truth.',
    date: '2025-09-11T13:45:00Z',
    author: 'Thomas Wright',
    nickname: 'practice_thomas',
    image: 'https://example.com/images/sketchbook_progress.jpg',
    thumbnail: 'sketchbook_progress.jpg',
    ups: 19,
    lang: 'eng',
  },
  {
    id: '2zwjxbsx76803',
    title: 'Как я начал бегать и не бросил',
    text: 'Первый раз я пробежал 400 метров и чуть не умер. Но вместо того чтобы ставить цель “бегать 5 км”, я сказал себе: “Выходи на улицу каждый день. Даже если просто постоишь”. Иногда я шёл, иногда — бежал минуту. Через месяц я уже бегал 20 минут без остановки. Секрет? Не в силе воли, а в системе. Я клал кроссовки у двери, выбирал приятную музыку и не ругал себя за пропуски. Бег стал ритуалом, а не обязанностью. Сейчас прошёл свой первый полумарафон. Вы не должны быть спортсменом, чтобы начать. Просто начните — с того, что кажется смешным. Постепенно это станет частью вас.',
    date: '2025-10-03T07:10:00Z',
    author: 'Илья Никитин',
    nickname: 'run_with_ilya',
    image: 'https://example.com/images/first_run.jpg',
    thumbnail: 'first_run.jpg',
    ups: 12,
    lang: 'ru',
  },
  {
    id: 'vge61qlx76803',
    title: 'Digital gardens: a better way to share ideas',
    text: 'Instead of chasing likes on social media, I started a digital garden — a personal website where I share half-formed thoughts, notes, and experiments. No algorithms, no virality pressure. Just a quiet space to think in public. Over time, it became my second brain and attracted kindred spirits. Digital gardens aren’t about perfection; they’re about growth. If you’re tired of performing online, consider planting one. Write for yourself first. The right people will find you.',
    date: '2025-11-05T15:55:00Z',
    author: 'Nina Patel',
    nickname: 'garden_nina',
    image: 'https://example.com/images/digital_garden.jpg',
    thumbnail: 'digital_garden.jpg',
    ups: 5,
    lang: 'eng',
  },
  {
    id: 'cxp7u9ux76803',
    title: 'Утро решает всё',
    text: 'Начните день с 10 минут медитации и стакана воды. Это простое правило кардинально улучшит вашу продуктивность и настроение. Не откладывайте — попробуйте уже завтра!',
    date: '2025-11-10T07:30:00Z',
    author: 'Анна Mindful Петрова',
    nickname: 'mindful_anna',
    image: 'https://example.com/images/morning_routine.jpg',
    thumbnail: 'morning_routine.jpg',
    ups: 18,
    lang: 'ru',
  },
  {
    id: 'zzds705x76803',
    title: 'Будущее за зелёной энергетикой',
    text: 'Солнечные панели стали на 40% дешевле за последние 5 лет. Это отличная возможность для каждого внести вклад в устойчивое будущее и сэкономить на электричестве.',
    date: '2025-11-10T09:15:00Z',
    author: 'Дмитрий Eco Соколов',
    nickname: 'eco_dmitry',
    image: 'https://example.com/images/solar_panels.jpg',
    thumbnail: 'solar_panels.jpg',
    ups: 22,
    lang: 'ru',
  },
  {
    id: 'ai41hf4x76803',
    title: 'Простой способ быть счастливее',
    text: 'Каждый вечер записывайте три хорошие вещи, которые произошли за день. Через месяц вы заметите, как изменилось ваше восприятие жизни. Психология подтверждает!',
    date: '2025-11-10T10:45:00Z',
    author: 'Елена Happy Ковалёва',
    nickname: 'happy_lena',
    image: 'https://example.com/images/gratitude_journal.jpg',
    thumbnail: 'gratitude_journal.jpg',
    ups: 14,
    lang: 'ru',
  },
  {
    id: '1rkko3nx76803',
    title: 'Код — это поэзия',
    text: 'Хороший программист не просто пишет код — он создаёт читаемое, элегантное решение. Не забывайте: вы пишете для людей, а не только для машин.',
    date: '2025-11-10T12:00:00Z',
    author: 'Михаил Code Poet Матвеев',
    nickname: 'code_poet',
    image: 'https://example.com/images/clean_code.jpg',
    thumbnail: 'clean_code.jpg',
    ups: 25,
    lang: 'ru',
  },
  {
    id: 'ftccgtgx76803',
    title: 'Гуляй, мозг!',
    text: 'Прогулка на свежем воздухе повышает креативность на 60%. Если застряли в задаче — выйдите на улицу. Иногда лучшие идеи приходят в движении.',
    date: '2025-11-10T13:20:00Z',
    author: 'Мария Walkthink Иванова',
    nickname: 'walk_and_think',
    image: 'https://example.com/images/walking_ideas.jpg',
    thumbnail: 'walking_ideas.jpg',
    ups: 9,
    lang: 'ru',
  },
  {
    id: '2ry5duhx76803',
    title: 'Маленькие шаги — большой результат',
    text: 'Читайте по 5 страниц в день — за год вы прочтёте больше 15 книг. Начинайте с малого, но регулярно. Время работает на вас.',
    date: '2025-11-10T14:50:00Z',
    author: 'Сергей Steady Новиков',
    nickname: 'steady_sergey',
    image: 'https://example.com/images/reading_habit.jpg',
    thumbnail: 'reading_habit.jpg',
    ups: 21,
    lang: 'ru',
  },
  {
    id: 'mp2kadmx76803',
    title: 'Цифровой детокс',
    text: 'Попробуйте выключить все уведомления на один вечер. Вы удивитесь, сколько глубоких разговоров и спокойствия может принести всего пара часов без экрана.',
    date: '2025-11-10T16:10:00Z',
    author: 'Ольга Offline Смирнова',
    nickname: 'offline_olga',
    image: 'https://example.com/images/digital_detox.jpg',
    thumbnail: 'digital_detox.jpg',
    ups: 17,
    lang: 'ru',
  },
  {
    id: 'xva4icgx76803',
    title: 'Завтрак чемпиона',
    text: 'Овсянка с ягодами, орехами и ложкой мёда — идеальное топливо для утра. Просто, полезно и вкусно. Забудьте о спешке: утро стоит начинать с заботы о себе.',
    date: '2025-11-10T17:30:00Z',
    author: 'Иван Healthy Козлов',
    nickname: 'healthy_ivan',
    image: 'https://example.com/images/oatmeal_breakfast.jpg',
    thumbnail: 'oatmeal_breakfast.jpg',
    ups: 12,
    lang: 'ru',
  },
  {
    id: '4h1dnlmx76803',
    title: 'Научитесь говорить «нет»',
    text: 'Каждое «да» чему-то ненужному — это «нет» вашим целям и мечтам. Уважайте своё время. Границы — не эгоизм, а забота о себе.',
    date: '2025-11-10T18:45:00Z',
    author: 'Виктория Boundaries Зайцева',
    nickname: 'boundaries_vika',
    image: 'https://example.com/images/say_no.jpg',
    thumbnail: 'say_no.jpg',
    ups: 24,
    lang: 'ru',
  },
  {
    id: 'nt2juybx76803',
    title: 'Музыка для фокуса',
    text: 'Инструментальные треки без слов повышают концентрацию. Мой плейлист с лоу-фай хип-хопом помогает мне писать код без отвлечений по 2 часа подряд.',
    date: '2025-11-10T20:00:00Z',
    author: 'Алексей Focus Морозов',
    nickname: 'focus_alex',
    image: 'https://example.com/images/focus_music.jpg',
    thumbnail: 'focus_music.jpg',
    ups: 7,
    lang: 'ru',
  },
];

export default list;
